### ISSUE TITLE
zoxide not working 

### ISSUE THREAD

**Issue by abhinitrajput** [ChrisTitusTech/powershell-profile#86]
Hello Team,

After the latest changes, zoxide is not working find the snap below of error 
![image](https://github.com/ChrisTitusTech/powershell-profile/assets/84317888/39ba3bf5-b2f9-4572-b03e-8771902ff508) 
is anyone has faced the same issue 
Thanks in advance

**Comment by korneltlaczala** [comment]
Hey @abhinitrajput, it does work, it has just been changed

### Solution
Just use:
- `cd` instead of `z`
- `cdi` instead of `zi`

### Legacy solution

If you wish to keep using the old, shorter `z`, `zi`, you can edit your **`profile.ps1`** file
- Run `Edit-Profile` function
- Add this code to the file:
```
Set-Alias -Name z -Value __zoxide_z
Set-Alias -Name zi -Value __zoxide_zi
```
- Save the file

Once you reload the shell, you will have the old commands available

### Where was the change
Merging pull request https://github.com/ChrisTitusTech/powershell-profile/pull/70 changed the way your powershell session initializes zoxide
I believe (correct me if i'm wrong) that running the line
`Invoke-Expression (& { (zoxide init --cmd cd powershell | Out-String) })`
sets the alias of `cd` to `__zoxide_z` and alias of `cdi` to `__zoxide_zi`

You can see that here:
![image](https://github.com/ChrisTitusTech/powershell-profile/assets/90900140/7c85cd50-7322-47d4-8684-29d58255be00)

**Comment by abhinitrajput** [comment]
Hello @korneltlaczala 

"Thanks for clearing up the doubt."
